// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModelTodo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Complete             bool     `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelTodo) Reset()         { *m = ModelTodo{} }
func (m *ModelTodo) String() string { return proto.CompactTextString(m) }
func (*ModelTodo) ProtoMessage()    {}
func (*ModelTodo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *ModelTodo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelTodo.Unmarshal(m, b)
}
func (m *ModelTodo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelTodo.Marshal(b, m, deterministic)
}
func (m *ModelTodo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelTodo.Merge(m, src)
}
func (m *ModelTodo) XXX_Size() int {
	return xxx_messageInfo_ModelTodo.Size(m)
}
func (m *ModelTodo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelTodo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelTodo proto.InternalMessageInfo

func (m *ModelTodo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ModelTodo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ModelTodo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ModelTodo) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ModelTodo) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Res                  []*ModelTodo `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
	Err                  string       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetRes() []*ModelTodo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *ListResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Res                  *ModelTodo `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetRes() *ModelTodo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type PostRequest struct {
	Todo                 *ModelTodo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetTodo() *ModelTodo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type PostResponse struct {
	Res                  *ModelTodo `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetRes() *ModelTodo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *PostResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type CompleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteRequest) Reset()         { *m = CompleteRequest{} }
func (m *CompleteRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteRequest) ProtoMessage()    {}
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *CompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteRequest.Unmarshal(m, b)
}
func (m *CompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteRequest.Marshal(b, m, deterministic)
}
func (m *CompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteRequest.Merge(m, src)
}
func (m *CompleteRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteRequest.Size(m)
}
func (m *CompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteRequest proto.InternalMessageInfo

func (m *CompleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CompleteResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteResponse) Reset()         { *m = CompleteResponse{} }
func (m *CompleteResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteResponse) ProtoMessage()    {}
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{8}
}

func (m *CompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteResponse.Unmarshal(m, b)
}
func (m *CompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteResponse.Marshal(b, m, deterministic)
}
func (m *CompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteResponse.Merge(m, src)
}
func (m *CompleteResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteResponse.Size(m)
}
func (m *CompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteResponse proto.InternalMessageInfo

func (m *CompleteResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ClearCompleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCompleteRequest) Reset()         { *m = ClearCompleteRequest{} }
func (m *ClearCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*ClearCompleteRequest) ProtoMessage()    {}
func (*ClearCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{9}
}

func (m *ClearCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCompleteRequest.Unmarshal(m, b)
}
func (m *ClearCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCompleteRequest.Marshal(b, m, deterministic)
}
func (m *ClearCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCompleteRequest.Merge(m, src)
}
func (m *ClearCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_ClearCompleteRequest.Size(m)
}
func (m *ClearCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCompleteRequest proto.InternalMessageInfo

type ClearCompleteResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCompleteResponse) Reset()         { *m = ClearCompleteResponse{} }
func (m *ClearCompleteResponse) String() string { return proto.CompactTextString(m) }
func (*ClearCompleteResponse) ProtoMessage()    {}
func (*ClearCompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{10}
}

func (m *ClearCompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCompleteResponse.Unmarshal(m, b)
}
func (m *ClearCompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCompleteResponse.Marshal(b, m, deterministic)
}
func (m *ClearCompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCompleteResponse.Merge(m, src)
}
func (m *ClearCompleteResponse) XXX_Size() int {
	return xxx_messageInfo_ClearCompleteResponse.Size(m)
}
func (m *ClearCompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCompleteResponse proto.InternalMessageInfo

func (m *ClearCompleteResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*ModelTodo)(nil), "pb.ModelTodo")
	proto.RegisterType((*ListRequest)(nil), "pb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "pb.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*PostRequest)(nil), "pb.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "pb.PostResponse")
	proto.RegisterType((*CompleteRequest)(nil), "pb.CompleteRequest")
	proto.RegisterType((*CompleteResponse)(nil), "pb.CompleteResponse")
	proto.RegisterType((*ClearCompleteRequest)(nil), "pb.ClearCompleteRequest")
	proto.RegisterType((*ClearCompleteResponse)(nil), "pb.ClearCompleteResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0x49, 0xdb, 0xef, 0x97, 0xed, 0xa9, 0xfb, 0x41, 0x9c, 0x52, 0x8b, 0xe2, 0x56, 0x44,
	0xb6, 0xcb, 0x90, 0x89, 0x77, 0xc7, 0x84, 0x5d, 0x14, 0xa4, 0x78, 0x97, 0x6d, 0x79, 0x0f, 0x83,
	0x69, 0x6a, 0x9b, 0x81, 0x57, 0x8f, 0xfe, 0xd7, 0x92, 0x34, 0x6b, 0xb7, 0xb2, 0x81, 0x78, 0x4b,
	0xde, 0x27, 0xf9, 0xe4, 0x7d, 0x9e, 0xb7, 0x05, 0x94, 0x14, 0x72, 0x98, 0xa4, 0x52, 0x49, 0xee,
	0x24, 0xf3, 0xe8, 0x9b, 0xa1, 0xfe, 0x24, 0x05, 0xad, 0x5e, 0xa4, 0x90, 0xbc, 0x09, 0x67, 0x29,
	0x02, 0xd6, 0x65, 0xfd, 0x7a, 0xec, 0x2c, 0x05, 0xbf, 0x00, 0x16, 0x29, 0xcd, 0x14, 0x89, 0xd7,
	0x99, 0x0a, 0x1c, 0x53, 0xaf, 0xdb, 0xca, 0x58, 0x69, 0x79, 0x9d, 0x88, 0x8d, 0xec, 0xe6, 0xb2,
	0xad, 0x8c, 0x15, 0xe7, 0xf0, 0x14, 0x7d, 0xaa, 0xc0, 0x33, 0x82, 0x59, 0xf3, 0x10, 0xb5, 0x85,
	0x7c, 0x4b, 0x56, 0xa4, 0x28, 0xf8, 0xd7, 0x65, 0xfd, 0x5a, 0x5c, 0xec, 0xa3, 0x06, 0xfc, 0xc7,
	0x65, 0xa6, 0x62, 0xfa, 0x58, 0x53, 0xa6, 0xa2, 0x31, 0x8e, 0xf2, 0x6d, 0x96, 0xc8, 0xf7, 0x8c,
	0xf8, 0x25, 0xdc, 0x94, 0xb2, 0x80, 0x75, 0xdd, 0xbe, 0x3f, 0x6a, 0x0c, 0x93, 0xf9, 0xb0, 0x68,
	0x3c, 0xd6, 0x0a, 0x6f, 0xc3, 0xa5, 0x34, 0xb5, 0x6d, 0xea, 0x65, 0x74, 0x0e, 0x4c, 0x69, 0x03,
	0xac, 0xba, 0x8b, 0xee, 0xe1, 0x1b, 0xb5, 0xca, 0x67, 0xbf, 0xe6, 0xdf, 0xc0, 0x7f, 0x96, 0x45,
	0xc7, 0xbc, 0x07, 0x4f, 0xc7, 0xbb, 0x1f, 0x61, 0x24, 0x6d, 0x2a, 0xbf, 0xf1, 0xf7, 0x47, 0x7b,
	0x68, 0x4d, 0x6c, 0x64, 0x87, 0x9c, 0x5d, 0xa1, 0x5d, 0x1e, 0xb1, 0x2f, 0x59, 0x10, 0x2b, 0x41,
	0xa7, 0xe8, 0x4c, 0x56, 0x34, 0x4b, 0x2b, 0xb4, 0x68, 0x80, 0x93, 0x4a, 0xfd, 0x10, 0x62, 0xf4,
	0xe5, 0xc0, 0x33, 0x5f, 0xce, 0x00, 0x9e, 0x1e, 0x16, 0x6f, 0x69, 0x0b, 0x5b, 0x53, 0x0c, 0xdb,
	0x65, 0xc1, 0x52, 0xae, 0xe1, 0x4e, 0x49, 0xf1, 0xa6, 0x16, 0xca, 0xe9, 0x84, 0xad, 0x62, 0x6f,
	0xcf, 0x0d, 0xe0, 0xe9, 0xa8, 0x72, 0xe4, 0x56, 0xcc, 0x39, 0x72, 0x27, 0xc5, 0x3b, 0xd4, 0x36,
	0xcd, 0xf2, 0x63, 0xad, 0x56, 0x2c, 0x85, 0x9d, 0xdd, 0xa2, 0xbd, 0xf6, 0x80, 0xc6, 0x8e, 0x51,
	0x1e, 0x98, 0x63, 0x7b, 0x32, 0x09, 0xcf, 0xf6, 0x28, 0x39, 0x65, 0xfe, 0xdf, 0xfc, 0x4d, 0xb7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0xe0, 0x45, 0xda, 0x5b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	ClearComplete(ctx context.Context, in *ClearCompleteRequest, opts ...grpc.CallOption) (*ClearCompleteResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/pb.Todo/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/pb.Todo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/pb.Todo/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, "/pb.Todo/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) ClearComplete(ctx context.Context, in *ClearCompleteRequest, opts ...grpc.CallOption) (*ClearCompleteResponse, error) {
	out := new(ClearCompleteResponse)
	err := c.cc.Invoke(ctx, "/pb.Todo/ClearComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Post(context.Context, *PostRequest) (*PostResponse, error)
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	ClearComplete(context.Context, *ClearCompleteRequest) (*ClearCompleteResponse, error)
}

// UnimplementedTodoServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (*UnimplementedTodoServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTodoServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedTodoServer) Post(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (*UnimplementedTodoServer) Complete(ctx context.Context, req *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (*UnimplementedTodoServer) ClearComplete(ctx context.Context, req *ClearCompleteRequest) (*ClearCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearComplete not implemented")
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_ClearComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).ClearComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/ClearComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).ClearComplete(ctx, req.(*ClearCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Todo_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Todo_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Todo_Post_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Todo_Complete_Handler,
		},
		{
			MethodName: "ClearComplete",
			Handler:    _Todo_ClearComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
