### list todos
GET /items?q=all
Host: localhost:8180

### get todo
GET /items/0EO5SViJKeCO8RvsBeZE2
Host: localhost:8180

### post todo
POST /items
Host: localhost:8180

{
    "text": "gddg"
}
### Complete
PUT /items/xW2_5rUi5uvWLu45AFnmq
Host: localhost:8180

### clear complete

POST /items/clear
Host: localhost:8180