@hostname = http://localhost:8180


###
# @name add
POST {{hostname}}/items HTTP/1.1
Content-Type: application/json

{
    "text": "ee"
}


###
# @name list
# filter=all,active,complete
@filter = all
GET {{hostname}}/items/?filter={{filter}} HTTP/1.1


### 
# @name delete
DELETE {{hostname}}/items/{{list.response.body.data[0].id}} HTTP/1.1


###
# @name edit
PUT {{hostname}}/items/{{list.response.body.data[0].id}} HTTP/1.1
Content-Type: application/json

{
    "id": "{{list.response.body.data[0].id}}",
    "text": "111"
}


###
# @name complete
POSt {{hostname}}/items/completes/{{list.response.body.data[0].id}} HTTP/1.1


###
# @name completeAll
POST {{hostname}}/items/completes HTTP/1.1


###
# @name clear
POST {{hostname}}/items/clear