version: '3.1'

networks:
  integration:
    driver: bridge

services:
  todo_test:
    build:
      context: .
      dockerfile: ./deployments/docker/Dockerfile.test
    depends_on:
      - db
    networks:
      - integration

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    networks:
      - integration