version: '3.1'

networks:
  todo:
    driver: bridge

services:
#  todo:
#    build:
#      context: .
#      dockerfile: ./deployments/docker/Dockerfile
#    depends_on:
#      - db
#    ports:
#      - "8180:8180"
#      - "8181:8181"
#    environment:
#      QS_DB_HOST: db
#      QS_DB_PORT: 5432
#      QS_DB_USER: postgres
#      QS_DB_PASS: password
#      QS_DB: todo
#    restart: on-failure
#    networks:
#      - todo
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    networks:
      - todo