version: '3.1'

networks:
  todo:
    driver: bridge

services:
  # tictac_test:
  #   build:
  #     context: .
  #     dockerfile: ./deployments/docker/Dockerfile.test
  #   depends_on:
  #     - db
  #   networks:
  #     - todo
  todo-db:
    image: postgres:latest
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    networks:
      - todo