FROM golang:1.14-alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git build-base

# Set working directory
WORKDIR /go/src/github.com/cage1016/gokit-todo/

COPY . .

# Run tests
CMD go test -v -race -tags=integration -coverprofile integration_cover.out ./...